attach_duration_msec: null
attach_pid: null
config_dir: /opt/rocm-7.1.1/libexec/rocprofiler-compute/rocprof_compute_soc/analysis_configs
device: 0
dispatch: null
filter_blocks: []
format_rocprof_output: csv
hip_trace: false
join_type: grid
kernel: null
kernel_names: false
kokkos_trace: false
list_available_metrics: false
list_metrics: null
list_sets: false
loglevel: 20
mem_level: ALL
mode: profile
name: bmm3
no_roof: false
path: /workspace/batched_gemm/workloads/bmm3/MI300X_A1
pc_sampling_interval: 1048576
pc_sampling_method: stochastic
quiet: false
remaining: ./batched_gemm
retain_rocpd_output: false
rocprofiler_sdk_library_path: /opt/rocm/lib/librocprofiler-sdk.so
roof_only: false
roofline_data_type:
- FP32
set_selected: null
sort: kernels
spatial_multiplexing: null
specs: false
subpath: gpu_model
target: null
verbose: 0
